---
name: ShellCheck

on:
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        # via https://github.com/marketplace/actions/shellcheck
      - name: Run ShellCheck
        uses: bi1yeu/action-shellcheck@exact-path-matching-ignore-path
        id: check
        with:
          ignore_paths: ./examples/bad.sh # exact path is matched
