---
name: ShellCheck

on:
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        # via https://github.com/marketplace/actions/shellcheck
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: examples/bad.sh
