---
name: ShellCheck

on:
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        # via https://github.com/marketplace/actions/shellcheck
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          # ignore_names: examples/bad.sh # does not work
          ignore_names: ./examples/bad.sh
